import Head from "next/head";
import FirstScreen from "../components/FirstScreen/FirstScreen";
import SecondSlide from "../components/SecondSlide";
import ThirdSlide from "../components/ThirdSlide";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FirstScreen />
      <SecondSlide />
      <ThirdSlide />
    </>
  );
}
